name: nwchem_shifter

on:
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  docker_schedule:
    if: (github.event_name == 'workflow_dispatch') || (github.event_name == 'schedule')
    strategy:
        fail-fast: false
        matrix:
          folder:
            - nwchem-702.mpipr.nersc
          archs: [linux/amd64]
    runs-on: ubuntu-18.04
    timeout-minutes: 420
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Qemu
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: crazymax/binfmt:v6.0.0
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: ${{ github.actor == github.repository_owner }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Arch
        id: get-arch
        run: |
          echo "::set-output name=arch::$(echo ${{matrix.archs }} | sed 's/linux//'|sed  's/\///g' )"
        shell: bash
      - name: build_schedule
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.actor == github.repository_owner }}
          context: ${{ matrix.folder }}
          platforms: ${{ matrix.archs }}
          tags: nwchemorg/${{ matrix.folder }}/${{ steps.get-arch.outputs.arch }}:testing
      - name: load and test image
        if:  ( github.actor == github.repository_owner )
        run: |
          docker pull nwchemorg/${{ matrix.folder }}/${{ steps.get-arch.outputs.arch }}:testing
          cd /tmp
          umask u=rwx,g=rwx,o=rwx
          umask -S
          svn export https://github.com/nwchemgit/nwchem/trunk/QA >& svnout.log
          cd QA
          docker run --rm  \
          -e NWCHEM_EXECUTABLE=/opt/nwchem-7.0.2/bin/nwchem --entrypoint='/opt/nwchem/QA/runtests.mpi.unix' \
          -v `pwd`:/opt/nwchem/QA ghcr.io/${{ github.actor }}/${{ matrix.folder }}/${{ steps.get-arch.outputs.arch }} \
          procs 2 h2o_opt prop_mep_gcube 
