name: nwchem_shifter

on:
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  docker_schedule:
    if: (github.event_name == 'workflow_dispatch') || (github.event_name == 'schedule')
    strategy:
        fail-fast: false
        matrix:
          folder:
            - nwchem-dev.mpipr.nersc
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: ${{ github.actor == github.repository_owner }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build_docker
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.actor == github.repository_owner }}
          context: ${{ matrix.folder }}
          tags: ghcr.io/${{ github.actor }}/${{ matrix.folder }}
#          tags: nwchemorg/${{ matrix.folder }}
      - name: load and test image
        if:  ( github.actor == github.repository_owner )
        run: |
#          docker pull nwchemorg/${{ matrix.folder }}
          docker pull ghcr.io/${{ github.actor }}/${{ matrix.folder }}
          cd /tmp
          umask u=rwx,g=rwx,o=rwx
          umask -S
          svn export https://github.com/nwchemgit/nwchem/trunk/QA >& svnout.log
          cd QA
          docker run --rm  \
          -v `pwd`:/opt/nwchem/QA --entrypoint='/opt/nwchem/QA/runtests.mpi.unix' \
          nwchemorg/${{ matrix.folder }} \
          procs 2 h2o_opt prop_mep_gcube 
